"""
Fetches the current S&P 500 constituent list from Wikipedia and writes
config/universe.yaml in the format expected by the APM pipeline.

Run: python scripts/generate_universe.py
"""

from __future__ import annotations

import sys
from pathlib import Path

import pandas as pd
import yaml


SECTOR_MAP = {
    "Information Technology":   "Technology",
    "Health Care":               "Health_Care",
    "Communication Services":    "Communication_Services",
    "Consumer Discretionary":    "Consumer_Discretionary",
    "Consumer Staples":          "Consumer_Staples",
    "Real Estate":               "Real_Estate",
    "Energy":                    "Energy",
    "Materials":                 "Materials",
    "Financials":                "Financials",
    "Industrials":               "Industrials",
    "Utilities":                 "Utilities",
}

DEMO_TICKERS = [
    "XOM", "CVX", "FCX", "JPM", "ABBV", "MPC", "MSFT", "KO",
    "NVDA", "LLY", "AAPL", "META", "NEE", "CAT", "AMZN",
]


def fetch_sp500() -> pd.DataFrame:
    import io, requests
    url = "https://en.wikipedia.org/wiki/List_of_S%26P_500_companies"
    resp = requests.get(url, verify=False, timeout=30,
                        headers={"User-Agent": "Mozilla/5.0"})
    resp.raise_for_status()
    tables = pd.read_html(io.StringIO(resp.text), attrs={"id": "constituents"})
    df = tables[0]
    df.columns = [c.strip() for c in df.columns]
    # Normalize ticker: Wikipedia uses periods (BRK.B) — yfinance uses hyphens (BRK-B)
    df["Symbol"] = df["Symbol"].str.replace(".", "-", regex=False)
    return df


def build_universe(df: pd.DataFrame) -> dict:
    sectors: dict[str, list] = {v: [] for v in SECTOR_MAP.values()}

    for _, row in df.iterrows():
        raw_sector = row.get("GICS Sector", "")
        sector = SECTOR_MAP.get(raw_sector)
        if sector is None:
            print(f"  WARNING: unknown sector '{raw_sector}' for {row['Symbol']} — skipping", file=sys.stderr)
            continue
        ticker = row["Symbol"].strip()
        name = row["Security"].strip()
        sectors[sector].append({"ticker": ticker, "name": name, "market_cap": "large"})

    # Remove empty sectors (shouldn't happen but safety)
    sectors = {k: v for k, v in sectors.items() if v}
    return {
        "sectors": sectors,
        "demo_deep_dive_tickers": DEMO_TICKERS,
    }


def main() -> None:
    print("Fetching S&P 500 from Wikipedia…")
    try:
        df = fetch_sp500()
    except Exception as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        sys.exit(1)

    print(f"  {len(df)} tickers found")
    universe = build_universe(df)

    total = sum(len(v) for v in universe["sectors"].values())
    print(f"  {total} tickers across {len(universe['sectors'])} sectors")
    for sec, tickers in universe["sectors"].items():
        print(f"    {sec}: {len(tickers)}")

    out = Path(__file__).parent.parent / "config" / "universe.yaml"
    header = (
        "# S&P 500 constituent universe — auto-generated by scripts/generate_universe.py\n"
        "# Source: Wikipedia List of S&P 500 companies (fetched live)\n"
        "# market_cap: all 'large' (S&P 500 = large-cap by definition)\n"
        "# Re-run the script after quarterly index rebalances to stay current.\n\n"
    )
    with open(out, "w") as f:
        f.write(header)
        yaml.dump(universe, f, default_flow_style=False, sort_keys=False, allow_unicode=True)

    print(f"\nWritten to {out}")


if __name__ == "__main__":
    main()
